#!/bin/sh

switch_home(){
    # -a: Recursively copies files and preserves symbolic links, permissions, timestamps, and other metadata.
    # -v: Provides detailed information about the transfer process.
    # -P: Shows progress during transfer and allows resuming of partially transferred files.
    # -h: Outputs file sizes in a human-readable format
    # -u: Skips files that are newer on the destination.
    rsync -avPhu home/sean/ /home/sean
}

switch_sys(){
    sudo rsync -avPhu system/ /
}

get_status(){
    rsync -anc --out-format="%n,%i" home/sean/ /home/sean
}

case "$1" in
    "switchhome") switch_home ;;
    "switchsys") switch_sys ;;
    "status") get_status ;;
esac
