msg-module=yes

osd-bar-align-x=0
osd-bar-align-y=1
osd-bar-h=2
osd-bar-w=100
osd-border-size=2
osd-font="Noto Sans"
osd-font-size=15

sub-ass-force-margins=yes
sub-back-color=0.0/0.0/0.0/0.50
sub-border-color=0.0/0.0/0.0/0.0
sub-color=1.0/1.0/1.0/1.0
sub-fix-timing=no
sub-font="Noto Sans"
sub-font-size=15
sub-use-margins=yes
